---
# 📌 Generate Unique Run ID
Generate_UID:
  description: Generate a unique run_id for the workflow execution.
  expected_output: A unique identifier string for tracking workflow execution
  async_execution: false
  agent: UIDGeneratorAgent
  input_keys:
    - "prefix"
  output_keys:
    - "run_id"

# 📌 Extract Brand Context based on User Prompt
Understand_Brand_Context:
  description: >
    Decode the user prompt '{user_prompt}' to articulate core brand elements following
    Alina Wheeler's 'Designing Brand Identity' methodology. This involves transforming the
    user's input into a structured Brand Identity Brief, clarifying the brand's identity,
    target audience, and market positioning. This provides a foundational understanding
    for subsequent agent analyses.
  expected_output: >
    A structured Brand Identity Brief containing all extracted elements.
  async_execution: false
  agent: BrandContextExpert
  input_keys:
    - "{run_id}"
    - "{user_prompt}"
  output_keys:
    - "{run_id}"
    - "{brand_promise}"
    - "{brand_values}"
    - "{brand_personality}"
    - "{brand_tone_of_voice}"
    - "{brand_purpose}"
    - "{brand_mission}"
    - "{target_audience}"
    - "{customer_needs}"
    - "{market_positioning}"
    - "{competitive_landscape}"
    - "{industry_focus}"
    - "{industry_trends}"
    - "{brand_identity_brief}"
  supabase_table: "brand_context"

# 📌 Generate Brand Name Ideas
Generate_Brand_Name_Ideas:
  description: >
    Strategically generate brand name candidates based on the Brand Identity Brief
    provided by the Brand Context Expert. Employ Alina Wheeler's methodology from
    'Designing Brand Identity' and industry best practices to ensure each name aligns
    with core brand attributes, target audience preferences, and market
    differentiation needs. This process should result in a diverse and compelling set
    of brand names that are memorable, distinctive, and relevant to the target audience.
  expected_output: >
    A structured Brand Name Generation Report, including details about each name.
  async_execution: false
  agent: BrandNameCreationExpert
  input_keys:
    - "{run_id}"
    - "{brand_context}"
    - "{brand_values}"
    - "{purpose}"
    - "{key_attributes}"
  output_keys:
    - "{run_id}"
    - "{brand_name}"
    - "{naming_category}"
    - "{brand_personality_alignment}"
    - "{brand_promise_alignment}"
    - "{target_audience_relevance}"
    - "{market_differentiation}"
    - "{memorability_score}"
    - "{pronounceability_score}"
    - "{visual_branding_potential}"
    - "{name_generation_methodology}"
    - "{timestamp}"
    - "{rank}"
  supabase_table: "brand_name_generation"

# 📌 Perform Semantic Analysis
Conduct_Semantic_Analysis:
  description: >
    Analyze the denotative, connotative, and linguistic properties of each brand name 
    in its source language, ensuring clarity, positive associations, and strategic brand 
    alignment. This analysis should uncover hidden meanings, subconscious associations, 
    and cultural nuances that can impact how the name is perceived, following Alina 
    Wheeler's 'Designing Brand Identity' framework.
  expected_output: >
    A Semantic Analysis & Brand Meaning Report, including details about each name.
  async_execution: true
  agent: SemanticAnalysisExpert
  input_keys:
    - "{run_id}"
    - "{brand_name_suggestions}"  # Pass the entire list of brand names
    - "{brand_context}"
    - "{brand_values}"
  output_keys:
    - "{run_id}"
    - "{task_name}"
    - "{brand_name}"
    - "{denotative_meaning}"
    - "{etymology}"
    - "{descriptiveness}"
    - "{concreteness}"
    - "{emotional_valence}"
    - "{brand_personality}"
    - "{sensory_associations}"
    - "{figurative_language}"
    - "{ambiguity}"
    - "{irony_or_paradox}"
    - "{humor_playfulness}"
    - "{phoneme_combinations}"
    - "{sound_symbolism}"
    - "{rhyme_rhythm}"
    - "{alliteration_assonance}"
    - "{word_length_syllables}"
    - "{compounding_derivation}"
    - "{brand_name_type}"
    - "{memorability_score}"
    - "{pronunciation_ease}"
    - "{clarity_understandability}"
    - "{uniqueness_differentiation}"
    - "{brand_fit_relevance}"
    - "{semantic_trademark_risk}"
    - "{rank}"
  supabase_table: "semantic_analysis"

# 📌 Conduct Linguistic Analysis
Conduct_Linguistic_Analysis:
  description: >
    Conduct a deep linguistic and phonetic analysis of each proposed brand name, 
    evaluating pronunciation, sound symbolism, morphology, and syntactic integration 
    to ensure optimal linguistic appeal, memorability, and brand effectiveness. This 
    includes identifying potential linguistic pitfalls and areas of confusion across 
    the top 10 global languages.
  expected_output: >
    A Linguistic Analysis Report detailing phonological suitability, morphological 
    structure, syntactic integration, lexical uniqueness, and overall readability.
  async_execution: true
  agent: LinguisticAnalysisExpert
  input_keys:
    - "{run_id}"
    - "{brand_name_suggestions}"
    - "{brand_context}"
    - "{brand_values}"
  output_keys:
    - "{run_id}"
    - "{brand_name}"
    - "{pronunciation_ease}"
    - "{euphony_vs_cacophony}"
    - "{rhythm_and_meter}"
    - "{phoneme_frequency_distribution}"
    - "{sound_symbolism}"
    - "{word_class}"
    - "{morphological_transparency}"
    - "{grammatical_gender}"
    - "{inflectional_properties}"
    - "{ease_of_marketing_integration}"
    - "{naturalness_in_collocations}"
    - "{homophones_homographs}"
    - "{semantic_distance_from_competitors}"
    - "{neologism_appropriateness}"
    - "{overall_readability_score}"
    - "{notes}"
    - "{rank}"
  supabase_table: "linguistic_analysis"

# 📌 Conduct Cultural Sensitivity Analysis
Conduct_Cultural_Sensitivity_Analysis:
  description: >
    Conduct an in-depth cultural sensitivity and localization analysis to ensure that 
    proposed brand names are globally acceptable, free from unintended connotations, 
    and aligned with cultural, religious, and social norms. This includes identifying 
    potential risks and proposing adaptations to ensure seamless global adoption.
  expected_output: >
    A comprehensive Cultural Sensitivity & Localization Report, including details 
    about each name.
  async_execution: true
  agent: CulturalSensitivityExpert
  input_keys:
    - "{run_id}"
    - "{brand_name_suggestions}"
    - "{brand_context}"
    - "{brand_values}"
  output_keys:
    - "{run_id}"
    - "{brand_name}"
    - "{cultural_connotations}"
    - "{symbolic_meanings}"
    - "{alignment_with_cultural_values}"
    - "{religious_sensitivities}"
    - "{social_political_taboos}"
    - "{body_part_bodily_function_connotations}"
    - "{age_related_connotations}"
    - "{gender_connotations}"
    - "{regional_variations}"
    - "{historical_meaning}"
    - "{current_event_relevance}"
    - "{overall_risk_rating}"
    - "{notes}"
    - "{rank}"
  supabase_table: "cultural_sensitivity_analysis"

# 📌 Conduct Translation Analysis
Conduct_Translation_Analysis:
  description: >
    Ensure that proposed brand names translate effectively across key global markets, 
    preserving their intended meaning, phonetic appeal, and brand essence while 
    avoiding negative or unintended connotations. Provide recommendations for 
    adaptation where necessary to optimize cultural and linguistic fit.
  expected_output: >
    A Global Translation & Linguistic Adaptation Report, including details about each name.
  async_execution: true
  agent: TranslationAnalysisExpert
  input_keys:
    - "{run_id}"
    - "{brand_name_suggestions}"
  output_keys:
    - "{run_id}"
    - "{direct_translation}"
    - "{semantic_shift}"
    - "{target_language}"
    - "{pronunciation_difficulty}"
    - "{phonetic_similarity_undesirable}"
    - "{phonetic_retention}"
    - "{cultural_acceptability}"
    - "{adaptation_needed}"
    - "{proposed_adaptation}"
    - "{brand_essence_preserved}"
    - "{global_consistency_vs_localization}"
    - "{notes}"
    - "{rank}"
  supabase_table: "translation_analysis"

# 📌 Evaluate Brand Names
Evaluate_Brand_Name_Ideas:
  description: >
    Critically assess generated brand names based on strategic alignment, 
    distinctiveness, memorability, linguistic considerations, and competitive 
    differentiation. Ensure shortlisted names are not only creative but also 
    commercially viable, legally defensible, and aligned with the brand's strategic 
    vision. Use Alina Wheeler's branding methodology, competitive intelligence, and 
    linguistic best practices to rank, score, and provide detailed rationale for top 
    brand name contenders.
  expected_output: >
    A ranked shortlist of the top three (3) brand name candidates, with an evaluation 
    report containing details about each name.
  async_execution: false
  agent: BrandNameEvaluator
  input_keys:
    - "{run_id}"
    - "{brand_name_suggestions}"
    - "{semantic_analysis_output}"
    - "{linguistic_analysis_output}"
    - "{cultural_sensitivity_output}"
    - "{translation_analysis_output}"
  output_keys:
    - "{run_id}"
    - "{brand_name}"  # Individual brand name
    - "{strategic_alignment_score}"
    - "{distinctiveness_score}"
    - "{competitive_advantage}"
    - "{brand_fit_score}"
    - "{positioning_strength}"
    - "{memorability_score}"
    - "{pronounceability_score}"
    - "{meaningfulness_score}"
    - "{phonetic_harmony}"
    - "{visual_branding_potential}"
    - "{storytelling_potential}"
    - "{domain_viability_score}"
    - "{overall_score}"
    - "{shortlist_status}"
    - "{evaluation_comments}"
    - "{rank}"
  supabase_table: "brand_name_evaluation"

# 📌 Conduct Domain Search
Conduct_Domain_Search:
  description: >
    Evaluate the digital branding and domain viability of each shortlisted brand name, 
    ensuring it is available, SEO-friendly, and secure for long-term use. This includes 
    assessing domain availability, acquisition costs, SEO optimization, brand consistency 
    across digital platforms, security risks, and scalability for future expansion.
  expected_output: >
    A Domain Strategy & Digital Viability Report, including details about each name.
  async_execution: false
  agent: DomainAnalysisExpert
  rpm_limit: 60  # Domainr API typically has rate limits
  rate_limit_strategy: "batch_and_wait"  # Process in batches with waiting periods
  input_keys:
    - "{run_id}"
    - "{ranked_brand_names}"
  output_keys:
    - "{run_id}"
    - "{brand_name}"
    - "{domain_exact_match}"
    - "{alternative_tlds}"
    - "{misspellings_variations_available}"
    - "{domain_history_reputation}"
    - "{acquisition_cost}"
    - "{seo_keyword_relevance}"
    - "{domain_length_readability}"
    - "{hyphens_numbers_present}"
    - "{brand_name_clarity_in_url}"
    - "{social_media_availability}"
    - "{idn_support_needed}"
    - "{security_privacy_recommendations}"
    - "{scalability_future_proofing}"
    - "{notes}"  # For any additional comments or observations
    - "{rank}"  # Overall domain viability ranking
  supabase_table: "domain_analysis"

# 📌 Analyze SEO and Online Discoverability
Analyze_SEO_and_Online_Discoverability:
  description: >
    Analyze brand name candidates for search engine optimization (SEO), 
    discoverability, and digital competitiveness to maximize online visibility 
    and brand marketability. This includes evaluating keyword alignment, search 
    volume, competition, social media presence, and potential risks.
  expected_output: >
    A comprehensive SEO and Online Discoverability Report, including details about each name.
  async_execution: false
  agent: SEOOnlineDiscoveryExpert
  rpm_limit: 60  # Google Search API typically has rate limits
  rate_limit_strategy: "batch_and_wait"
  batch_size: 10  # Process 10 queries at a time
  input_keys:
    - "{run_id}"
    - "{ranked_brand_names}"
  output_keys:
    - "{run_id}"
    - "{brand_name}"
    - "{keyword_alignment}"
    - "{search_volume}"
    - "{keyword_competition}"
    - "{branded_keyword_potential}"
    - "{non_branded_keyword_potential}"
    - "{exact_match_search_results}"
    - "{competitor_domain_strength}"
    - "{name_length_searchability}"
    - "{unusual_spelling_impact}"
    - "{content_marketing_opportunities}"
    - "{social_media_availability}"
    - "{social_media_discoverability}"
    - "{negative_keyword_associations}"
    - "{negative_search_results}"
    - "{seo_viability_score}"
    - "{seo_recommendations}"
    - "{timestamp}"
  supabase_table: "seo_online_discoverability"

# 📌 Analyze Competitor Names
Analyze_Competitor_Names:
  description: >
    Analyze competitor brand names within the competitive landscape to assess proposed 
    brand names and identify opportunities for differentiation. This involves understanding 
    market dynamics, competitor positioning, and the nuances of brand naming within 
    various industries.
  expected_output: >
    A Competitor Analysis Report including:
      - A competitive landscape analysis of naming styles, themes, and brand positioning.
      - A differentiation score for each proposed brand name.
      - An assessment of name distinctiveness, competitive risk, and industry white space opportunities.
      - Identification of competitors with similar names or branding risks.
      - Strategic recommendations for refining or adjusting the proposed names.
  async_execution: false
  agent: CompetitorAnalysisExpert
  input_keys:
    - "{run_id}"
    - "{brand_context}"
    - "{brand_name_suggestions}"
  output_keys:
    - "{run_id}"
    - "{competitor_name}"
    - "{competitor_naming_style}"
    - "{competitor_keywords}"
    - "{competitor_positioning}"
    - "{competitor_strengths}"
    - "{competitor_weaknesses}"
    - "{competitor_differentiation_opportunity}"
    - "{brand_name}"
    - "{differentiation_score}"
    - "{risk_of_confusion}"
    - "{target_audience_perception}"
    - "{competitive_advantage_notes}"
    - "{trademark_conflict_risk}"
    - "{timestamp}"
  supabase_table: "competitor_analysis"

# 📌 Conduct Survey Simulation
Conduct_Survey_Simulation:
  description: >
    Simulate high-precision, AI-driven market research that mirrors enterprise-level 
    survey methodologies, generating deep, behavioral insights on how shortlisted brand 
    names resonate across segmented target audiences. Provide data-backed, statistically 
    robust name performance assessments that drive high-stakes branding decisions.
  expected_output: >
    An Enterprise AI-Driven Brand Name Perception Report, including details about each name.
  async_execution: false
  agent: SurveySimulationExpert
  input_keys:
    - "{run_id}"
    - "{ranked_brand_names}"
  output_keys:
    - "{run_id}"
    - "{brand_name}"
    - "{persona_segment}"
    - "{brand_promise_perception_score}"
    - "{personality_fit_score}"
    - "{emotional_association}"
    - "{functional_association}"
    - "{competitive_differentiation_score}"
    - "{psychometric_sentiment_mapping}"
    - "{competitor_benchmarking_score}"
    - "{simulated_market_adoption_score}"
    - "{qualitative_feedback_summary}"
    - "{raw_qualitative_feedback}"
    - "{final_survey_recommendation}"
    - "{strategic_ranking}"
    - "{timestamp}"
  supabase_table: "survey_simulation"

# 📌 Supervise Process
Supervise_Process:
  description: >
    Monitor all stages of the process, log intermediate outputs, track task 
    statuses, manage retries, and escalate errors to ensure a smooth and 
    efficient workflow. Ensure that each task is executed accurately, 
    efficiently, and within expected parameters.
  expected_output: >
    A detailed process log capturing execution statuses, retries, errors, 
    durations, and task completion states, stored in Supabase.
  async_execution: false
  agent: ProcessSupervisor
  input_keys:
    - "{run_id}"
  output_keys:
    - "{run_id}"
    - "{agent_type}"
    - "{task_name}"
    - "{status}"
    - "{start_time}"
    - "{end_time}"
    - "{duration_sec}"
    - "{error_message}"
    - "{last_updated}"
    - "{retry_count}"
    - "{last_retry_at}"
    - "{retry_status}"
    - "{execution_duration_ms}"
    - "{input_size_kb}"
    - "{output_size_kb}"
  supabase_table: "process_logs"

# 📌 Compile and Format Report
Compile_And_Format_Report:
  description: >
    Aggregate and synthesize all brand naming analyses into a structured, enterprise-grade 
    report, ensuring clarity, strategic insights, and executive-ready presentation. This 
    involves transforming raw analytical insights into a highly professional, logically 
    structured report, formatted for clarity, strategic decision-making, and high-impact 
    brand presentations.
  expected_output: >
    A structured and finalized Brand Naming Report, stored in Supabase.
  async_execution: false
  agent: ReportCompilationExpert
  input_keys:
    - "{run_id}"
  output_keys:
    - "{run_id}"
    - "{report_url}"
    - "{version}"
    - "{created_at}"
    - "{last_updated}"
    - "{format}"
    - "{file_size_kb}"
    - "{notes}"
  supabase_table: "report_compilation"

# 📌 Perform Quality Assurance
Perform_Quality_Assurance:
  description: >
    Conduct a comprehensive quality assurance check on all deliverables, 
    ensuring completeness, accuracy, coherence, and adherence to branding and 
    linguistic standards. Identify potential issues and provide structured feedback.
  expected_output: >
    A structured QA verification report with completeness, accuracy, and coherence assessment.
  async_execution: false
  agent: QualityAssuranceSpecialist
  input_keys:
    - "{run_id}"
    - "{report_url}"
  output_keys:
    - "{run_id}"
    - "{qa_notes}"
    - "{status}"
    - "{created_at}"
    - "{last_updated}"
  supabase_table: "quality_assurance_logs"
