[server]
# Explicitly set Python version
pythonVersion = "3.11"

[theme]
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[browser]
gatherUsageStats = false 